- name: test connection
  hosts: all
  become: yes
  
  tasks:
  - name: Ping servers
    ping:
    
ansible-playbook playbook1.yml

nano playbook2.yml

- name: install webserver
  hosts: all
  become: yes
  
  tasks:
  - name: install apache2
    apt: name=apache2 state=latest
    
  - name: start and enable apache2
    service: name=apache2 state=started enabled=yes
